'use client';
import Link from 'next/link';
import { useCallback,useEffect,useMemo,useState } from 'react';
import { CreditCard,Download,RefreshCw } from 'lucide-react';
import { PageIntro,Metric,control,surface,number } from '@/components/finanzas/finance-ui';
import { resumirTarjeta,periodoMesAnterior,type RegistroTarjeta } from '@/lib/tarjetas-informe';
import { todayBuenosAires } from '@/lib/cashflow-compute';
import { csvRegistros } from '@/lib/finanzas-registros';
import { descargarTexto } from '@/lib/descargar-texto';
import { useRealtimeTable } from '@/hooks/use-realtime-table';

type Cuenta={id:string;nombre:string;moneda:string;saldo:number;ultimoMovimiento:string|null;ultimoArqueo:{fecha:string;saldo_declarado:number}|null};
type Informe={id:string;creado_at:string;titulo:string;contenido:{resumen?:string[];fuentes?:{nombre:string;estado:string;detalle:string}[];pendientes?:string[]}};
type Data={hoy:string;actualizadoEn:string;cuentas:Cuenta[];registros:RegistroTarjeta[];informes:Informe[]};
const importe=(n:number,moneda:string)=>new Intl.NumberFormat('es-AR',{style:'currency',currency:moneda,maximumFractionDigits:2,minimumFractionDigits:Number.isInteger(n)?0:2}).format(n);
const fecha=(s:string)=>new Date(`${s.slice(0,10)}T12:00:00Z`).toLocaleDateString('es-AR');
const tipos={consumo:'Compra',reintegro:'Reintegro',pago:'Pago de tarjeta',ajuste:'Otro movimiento'};
export function TarjetasScreen(){
 const hoy=todayBuenosAires();
 const [datos,setDatos]=useState<Data|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const [desde,setDesde]=useState(`${hoy.slice(0,7)}-01`),[hasta,setHasta]=useState(hoy),[moneda,setMoneda]=useState('ARS');
 const [cuenta,setCuenta]=useState(''),[ambito,setAmbito]=useState(''),[categoria,setCategoria]=useState(''),[busqueda,setBusqueda]=useState(''),[clase,setClase]=useState('consumos'),[limite,setLimite]=useState(40);
 const cargar=useCallback(async(signal?:AbortSignal)=>{setLoading(true);try{const r=await fetch('/api/finanzas/tarjetas',{signal,cache:'no-store'});const b=await r.json();if(!r.ok)throw new Error(b.error);setDatos(b);setError('');}catch(e){if(!signal?.aborted)setError(e instanceof Error?e.message:'No se pudo leer el informe');}finally{if(!signal?.aborted)setLoading(false);}},[]);
 useEffect(()=>{const c=new AbortController();void cargar(c.signal);return()=>c.abort();},[cargar]);
 const refrescar=useCallback(()=>cargar(),[cargar]);useRealtimeTable('movimientos_plata',refrescar);useRealtimeTable('eventos',refrescar);
 const base=useMemo(()=>(datos?.registros??[]).filter(r=>r.moneda===moneda&&(!cuenta||r.cuenta_id===cuenta)),[datos,moneda,cuenta]);
 const relevantes=base.filter(r=>!ambito||r.ambito===ambito);
 const periodoValido=Boolean(desde&&hasta&&desde<=hasta&&hasta<=hoy);
 const resumen=resumirTarjeta(relevantes,desde,hasta,moneda);
 const anterior=periodoValido?periodoMesAnterior(desde,hasta):{desde:'',hasta:''};
 const previo=resumirTarjeta(relevantes,anterior.desde,anterior.hasta,moneda);
 const variacion=previo.neto>0?(resumen.neto-previo.neto)/previo.neto*100:null;
 const filtrados=relevantes.filter(r=>r.fecha>=desde&&r.fecha<=hasta&&(!categoria||r.categoria===categoria)&&(!clase||(clase==='consumos'?(r.clase==='consumo'||r.clase==='reintegro'):r.clase===clase))&&`${r.descripcion} ${r.obra} ${r.categoria}`.toLocaleLowerCase('es').includes(busqueda.toLocaleLowerCase('es'))).sort((a,b)=>b.fecha.localeCompare(a.fecha)||a.id.localeCompare(b.id));
 const futuras=base.filter(r=>r.fecha>hoy);
 const meses=new Map<string,number>();for(const r of relevantes.filter(r=>r.fecha<=hoy&&(r.clase==='consumo'||r.clase==='reintegro'))){const key=r.fecha.slice(0,7);meses.set(key,(meses.get(key)||0)+Math.round(r.importe*100));}
 const historia=[...meses].sort(([a],[b])=>a.localeCompare(b)).slice(-6);const maxMes=Math.max(1,...historia.map(([,v])=>v));const maxCategoria=Math.max(1,...resumen.categorias.map(c=>c.total));
 const nombreCuenta=(id:string)=>datos?.cuentas.find(c=>c.id===id)?.nombre??'Tarjeta';
 function mes(m:string){setDesde(`${m}-01`);const [y,n]=m.split('-').map(Number);const fin=new Date(Date.UTC(y,n,0)).toISOString().slice(0,10);setHasta(fin>hoy?hoy:fin);setCategoria('');setLimite(40);}
 function exportar(){descargarTexto(`RAVN_tarjetas_${desde}_${hasta}_${moneda}.csv`,csvRegistros(['Fecha','Tarjeta','Tipo','Concepto','Ámbito','Categoría','Obra','Importe concepto','Movimiento en cuenta','Moneda','ID'],filtrados.map(r=>[r.fecha,nombreCuenta(r.cuenta_id),tipos[r.clase],r.descripcion,r.ambito,r.categoria,r.obra,r.importe,r.monto,r.moneda,r.id])),'text/csv;charset=utf-8');}
 return <div className="mx-auto max-w-6xl px-4 py-6 pb-20 text-cdm-fg sm:px-8">
  <Link href="/finanzas" className="mb-5 inline-flex min-h-11 items-center text-sm text-cdm-muted">← Gastos personales</Link>
  <PageIntro eyebrow="Tu dinero" title="Tarjetas e informes" description="Qué gastaste, cuánto pagaste y dónde se fue. Personal, empresa y obras separados." action={<button className={`${control} inline-flex items-center gap-2`} onClick={()=>void cargar()} disabled={loading}><RefreshCw size={16}/>Actualizar</button>}/>
  <p className={`${surface} mb-5 p-4 text-sm leading-relaxed text-cdm-muted`}>Datos registrados en App RAVN. Los saldos del banco, cierres y vencimientos requieren una revisión bancaria actualizada; no son una conexión bancaria en vivo.</p>
  {error&&<p role="alert" className={`${surface} mb-4 p-4`}>{error} <button className="underline" onClick={()=>void cargar()}>Reintentar</button></p>}
  {loading&&<p role="status" className="mb-4 text-sm text-cdm-muted">Leyendo registros…</p>}
  {datos&&<>
   <section aria-label="Saldos registrados de tarjetas" className="mb-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{datos.cuentas.map(c=><button key={c.id} aria-pressed={cuenta===c.id} className={`${surface} p-4 text-left ${cuenta===c.id?'outline-2 outline-cdm-fg':''}`} onClick={()=>{setCuenta(cuenta===c.id?'':c.id);setMoneda(c.moneda);setCategoria('');}}><div className="mb-4 flex items-center gap-2 text-sm font-medium"><CreditCard size={17}/>{c.nombre}</div><Metric label={c.saldo>0?'A favor registrado':'Deuda registrada a hoy'} value={importe(Math.abs(c.saldo),c.moneda)}/><p className="mt-3 text-xs leading-relaxed text-cdm-muted">Último control: {c.ultimoArqueo?fecha(c.ultimoArqueo.fecha):'sin control registrado'}<br/>Último movimiento: {c.ultimoMovimiento?fecha(c.ultimoMovimiento):'sin registros'}</p></button>)}</section>
   <section aria-label="Período del informe" className={`${surface} mb-4 p-4`}><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><label className="text-xs text-cdm-muted">Desde<input className={`${control} mt-1 w-full`} type="date" value={desde} max={hoy} onChange={e=>{setDesde(e.target.value);setCategoria('');}}/></label><label className="text-xs text-cdm-muted">Hasta<input className={`${control} mt-1 w-full`} type="date" value={hasta} max={hoy} onChange={e=>{setHasta(e.target.value);setCategoria('');}}/></label><label className="text-xs text-cdm-muted">Moneda<select className={`${control} mt-1 w-full`} value={moneda} onChange={e=>{setMoneda(e.target.value);setCuenta('');setCategoria('');}}><option value="ARS">Pesos</option><option value="USD">Dólares</option></select></label><label className="text-xs text-cdm-muted">Ámbito<select className={`${control} mt-1 w-full`} value={ambito} onChange={e=>{setAmbito(e.target.value);setCategoria('');}}><option value="">Todos</option><option>Personal</option><option>Empresa</option><option>Obra</option></select></label></div><div className="mt-3 flex flex-wrap gap-2"><button className={control} onClick={()=>mes(hoy.slice(0,7))}>Este mes</button><button className={control} onClick={()=>mes(periodoMesAnterior(hoy,hoy).desde.slice(0,7))}>Mes anterior</button>{cuenta&&<button className={control} onClick={()=>setCuenta('')}>Todas las tarjetas</button>}</div></section>
   {!periodoValido?<p role="alert" className="p-4">Elegí un período válido que termine hoy o antes.</p>:<>
    <section aria-label="Consumos del período" className={`${surface} grid grid-cols-2 gap-5 p-5 lg:grid-cols-4`}><Metric label="Gasto neto registrado" value={importe(resumen.neto,moneda)} detail={`${resumen.cantidad} compras · ${fecha(desde)} a ${fecha(hasta)}`}/><Metric label="Consumos" value={importe(resumen.consumos,moneda)}/><Metric label="Reintegros" value={importe(resumen.reintegros,moneda)}/><Metric label="Pagos a la tarjeta" value={importe(resumirTarjeta(base,desde,hasta,moneda).pagos,moneda)} detail="Pagos registrados, no compras nuevas"/></section>
    <p className="my-3 text-sm leading-relaxed text-cdm-muted">{variacion===null?'Sin gasto previo registrado para comparar.':`${number(Math.abs(variacion))}% ${variacion>=0?'más':'menos'} que lo registrado del ${fecha(anterior.desde)} al ${fecha(anterior.hasta)} (${importe(previo.neto,moneda)}).`}</p>
    <div className="my-4 grid gap-4 md:grid-cols-2"><section className={`${surface} p-5`}><h2 className="mb-4 font-semibold">En qué se fue</h2>{resumen.categorias.length?resumen.categorias.map(c=><button key={c.nombre} className="mb-3 block min-h-11 w-full text-left" aria-pressed={categoria===c.nombre} onClick={()=>{setCategoria(categoria===c.nombre?'':c.nombre);setClase('consumos');setLimite(40);}}><span className="flex justify-between gap-3 text-sm"><span>{c.nombre}</span><strong className="shrink-0 tabular-nums">{importe(c.total,moneda)}</strong></span><span className="mt-2 block h-1.5 rounded-full bg-cdm-fg/10"><span className="block h-full rounded-full bg-cdm-fg/70" style={{width:`${Math.max(0,c.total)/maxCategoria*100}%`}}/></span></button>):<p className="text-sm text-cdm-muted">Sin consumos registrados en este período.</p>}<div className="mt-4 space-y-2 border-t border-cdm-line pt-4">{resumen.porAmbito.map(a=><p key={a.nombre} className="flex justify-between text-xs"><span>{a.nombre}</span><strong>{importe(a.total,moneda)}</strong></p>)}</div></section>
    <section className={`${surface} p-5`}><h2 className="font-semibold">Cómo viene el gasto</h2><p className="mb-5 mt-1 text-xs text-cdm-muted">Meses registrados · tocá uno para ver sus compras</p>{historia.map(([m,centavos])=><button className="mb-4 block min-h-11 w-full text-left" key={m} onClick={()=>mes(m)}><span className="flex justify-between gap-3 text-sm"><span>{new Date(`${m}-01T12:00:00Z`).toLocaleDateString('es-AR',{month:'long',year:'numeric'})}{m===hoy.slice(0,7)?' · a hoy':''}</span><strong className="shrink-0 tabular-nums">{importe(centavos/100,moneda)}</strong></span><span className="mt-2 block h-2 rounded-full bg-cdm-fg/10"><span className="block h-full rounded-full bg-cdm-fg/65" style={{width:`${Math.max(0,centavos)/maxMes*100}%`}}/></span></button>)}{!historia.length&&<p className="text-sm text-cdm-muted">Sin consumos registrados para esta selección.</p>}</section></div>
    {futuras.length>0&&<p className="my-4 text-xs text-cdm-muted">Hay {futuras.length} movimientos cargados con fecha futura. No se suman al gasto ni al saldo de hoy.</p>}
    <section aria-label="Detalle de la tarjeta"><div className="mb-3 flex flex-wrap gap-2"><input className={`${control} min-w-40 flex-1`} aria-label="Buscar consumo" placeholder="Buscar comercio, concepto u obra" value={busqueda} onChange={e=>{setBusqueda(e.target.value);setLimite(40);}}/><select aria-label="Tipo de movimiento" className={control} value={clase} onChange={e=>{setClase(e.target.value);setCategoria('');}}><option value="consumos">Compras y reintegros</option><option value="pago">Pagos de tarjeta</option><option value="ajuste">Otros movimientos</option><option value="">Todos los movimientos</option></select><button className={`${control} inline-flex items-center gap-2`} disabled={!filtrados.length||loading||!!error} onClick={exportar}><Download size={16}/>Exportar</button>{categoria&&<button className={control} onClick={()=>setCategoria('')}>{categoria} ×</button>}</div><p className="mb-3 text-xs text-cdm-muted">{filtrados.length} registros</p><div className={`${surface} overflow-hidden`}>{filtrados.slice(0,limite).map(r=><article key={r.id} className="flex items-start justify-between gap-4 border-b border-cdm-line p-4 last:border-0"><div className="min-w-0"><p className="break-words text-sm font-medium">{r.descripcion}</p><p className="mt-1 text-xs leading-relaxed text-cdm-muted">{fecha(r.fecha)} · {nombreCuenta(r.cuenta_id)} · {tipos[r.clase]}<br/>{r.ambito} · {r.categoria}{r.obra?` · ${r.obra}`:''}</p></div><strong className="shrink-0 text-sm tabular-nums">{importe(r.importe,r.moneda)}</strong></article>)}{!filtrados.length&&<p className="p-5 text-sm text-cdm-muted">No hay movimientos con estos filtros.</p>}</div>{filtrados.length>limite&&<button className={`${control} mt-3`} onClick={()=>setLimite(limite+50)}>Ver más movimientos</button>}</section>
   </>}
   <section aria-label="Informes de revisión" className="mt-8"><h2 className="mb-4 text-lg font-semibold">Últimas revisiones</h2>{datos.informes.map(i=><details key={i.id} className={`${surface} mb-3 p-4`} open={i===datos.informes[0]}><summary className="min-h-11 cursor-pointer text-sm font-semibold">{i.titulo}</summary><p className="mb-3 text-xs text-cdm-muted">{new Date(i.creado_at).toLocaleString('es-AR')}</p>{(i.contenido.resumen??[]).map((s,n)=><p key={n} className="mb-2 text-sm leading-relaxed">{s}</p>)}{i.contenido.fuentes?.length&&<div className="mt-4 grid gap-3 sm:grid-cols-2">{i.contenido.fuentes.map(f=><div key={f.nombre} className="rounded-xl border border-cdm-line p-3"><p className="text-sm font-semibold">{f.nombre} · {f.estado}</p><p className="mt-1 text-xs leading-relaxed text-cdm-muted">{f.detalle}</p></div>)}</div>}{(i.contenido.pendientes??[]).map((s,n)=><p key={n} className="mt-3 text-xs leading-relaxed text-cdm-muted">{s}</p>)}</details>)}{!datos.informes.length&&<p className="text-sm text-cdm-muted">Todavía no hay revisiones guardadas.</p>}</section>
   <p className="mt-6 text-xs text-cdm-muted">Lectura de la app: {new Date(datos.actualizadoEn).toLocaleString('es-AR')}.</p>
  </>}
 </div>;
}
