"use client";
import Link from "next/link";
import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {Download,Printer,Share2} from "lucide-react";
import {useReactToPrint} from "react-to-print";
import {todayBuenosAires} from "@/lib/cashflow-compute";
import {semanaRegistro,csvRegistros} from "@/lib/finanzas-registros";
import {resumenPagosTexto,type PagoPersonal} from "@/lib/registro-pagos";
import {descargarTexto} from "@/lib/descargar-texto";
import {PageIntro,Metric,control,money,number,surface} from "@/components/finanzas/finance-ui";
import {useRealtimeTable} from "@/hooks/use-realtime-table";
type Acuerdo={id:string;presupuestoId:string;persona:string;trabajo:string;moneda:string;arreglado:number;pagado:number;saldo:number;estado:string;notas:string|null;pagosSinCotizacion:number};
type Datos={pagos:PagoPersonal[];acuerdos:Acuerdo[]};
export function ManoObraGlobalScreen(){
  const [desde,setDesde]=useState(""),[hasta,setHasta]=useState(""),[persona,setPersona]=useState(""),[obra,setObra]=useState("");
  const [data,setData]=useState<Datos|null>(null),[error,setError]=useState(""),[aviso,setAviso]=useState(""),[limite,setLimite]=useState(40);const printRef=useRef<HTMLDivElement>(null);
  const cargar=useCallback(async()=>{try{const r=await fetch("/api/mano-obra/pagos",{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error);setData(j);setError("");}catch(e){setError(e instanceof Error?e.message:"No se pudo conectar.");}},[]);
  useEffect(()=>{void cargar();},[cargar]);useRealtimeTable("presupuestos_gastos",cargar);useRealtimeTable("mo_acuerdos",cargar);
  const personas=useMemo(()=>[...new Set([...(data?.pagos??[]).map(p=>p.persona),...(data?.acuerdos??[]).map(p=>p.persona)])].sort((a,b)=>a.localeCompare(b,"es")),[data]);
  const obras=useMemo(()=>[...new Map((data?.pagos??[]).map(p=>[p.presupuestoId,p.obra])).entries()].sort((a,b)=>a[1].localeCompare(b[1],"es")),[data]);
  const rangoInvalido=Boolean(desde&&hasta&&desde>hasta);
  const pagos=useMemo(()=>rangoInvalido?[]:(data?.pagos??[]).filter(p=>(!persona||p.persona===persona)&&(!obra||p.presupuestoId===obra)&&(!desde||p.fecha>=desde)&&(!hasta||p.fecha<=hasta)),[data,persona,obra,desde,hasta,rangoInvalido]);
  const acuerdos=(data?.acuerdos??[]).filter(a=>(!persona||a.persona===persona)&&(!obra||a.presupuestoId===obra));
  const total=pagos.reduce((n,p)=>n+Math.round(p.importe*100),0)/100;
  const deuda=acuerdos.filter(a=>a.moneda==="ARS"&&a.estado==="abierto").reduce((n,a)=>n+Math.round(Math.max(0,a.saldo)*100),0)/100;
  const texto=resumenPagosTexto(pagos,persona||"Todo el personal",desde,hasta);
  function setSemana(delta:number){const s=semanaRegistro(todayBuenosAires(),delta);setDesde(s.desde);setHasta(s.hasta);setLimite(40);}
  function exportar(){descargarTexto(`RAVN_pagos_${desde||"historial"}_${hasta||"completo"}.csv`,csvRegistros(["Operario","Fecha","Obra","Trabajo","Concepto","Importe ARS","Medio / cuenta","ID pago"],pagos.map(p=>[p.persona,p.fecha,p.obra,p.trabajo,p.descripcion,p.importe,p.cuenta,p.id])),"text/csv;charset=utf-8");}
  const imprimir=useReactToPrint({contentRef:printRef,documentTitle:`RAVN_Pagos_${persona||"personal"}_${desde}_${hasta}`,pageStyle:"@page {size:A4;margin:16mm} body{font-family:Arial,sans-serif;color:#111;background:white} table{width:100%;border-collapse:collapse} th,td{padding:9px 6px;border-bottom:1px solid #ddd;text-align:left;font-size:11px} tr{break-inside:avoid} h1{font-size:26px} h2{font-size:18px} p{font-size:12px}"});
  async function compartir(){setAviso("");try{if(navigator.share)await navigator.share({title:"RAVN · Resumen de pagos",text:texto});else{descargarTexto(`RAVN_resumen_pagos_${desde||"historial"}.txt`,texto);setAviso("Resumen descargado, listo para adjuntar.");}}catch(e){if(e instanceof Error&&e.name==="AbortError")return;descargarTexto("RAVN_resumen_pagos.txt",texto);setAviso("Resumen descargado, listo para adjuntar.");}}
  return <div className="font-raleway mx-auto max-w-6xl px-4 py-6 pb-16 text-cdm-fg sm:px-8"><PageIntro eyebrow="RAVN · Personal de obra" title="Cada pago, en orden." description="Elegí operario y período. El resumen usa exactamente los pagos que ves acá." action={<Link href="/gasto" className={control}>Registrar pago</Link>}/>
    <section className={`${surface} mb-5 p-4`}><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs text-cdm-muted">Operario<select value={persona} onChange={e=>{setPersona(e.target.value);setLimite(40);}} className={`${control} mt-1 w-full`}><option value="">Todo el personal</option>{personas.map(p=><option key={p}>{p}</option>)}</select></label><label className="text-xs text-cdm-muted">Obra<select value={obra} onChange={e=>setObra(e.target.value)} className={`${control} mt-1 w-full`}><option value="">Todas las obras</option>{obras.map(([id,n])=><option key={id} value={id}>{n}</option>)}</select></label><label className="text-xs text-cdm-muted">Desde<input type="date" value={desde} onChange={e=>setDesde(e.target.value)} className={`${control} mt-1 w-full`}/></label><label className="text-xs text-cdm-muted">Hasta<input type="date" value={hasta} onChange={e=>setHasta(e.target.value)} className={`${control} mt-1 w-full`}/></label></div><div className="mt-3 flex flex-wrap gap-2"><button className={control} onClick={()=>setSemana(0)}>Esta semana</button><button className={control} onClick={()=>setSemana(-1)}>Semana anterior</button><button className={`${control} ${!desde&&!hasta?"bg-cdm-fg/10":""}`} aria-pressed={!desde&&!hasta} onClick={()=>{setDesde("");setHasta("");setLimite(40);}}>Todo el historial</button></div></section>
    {error&&<p className={`${surface} mb-4 p-4 text-sm`} role="alert">{error} <button className="underline" onClick={()=>void cargar()}>Reintentar</button></p>}{rangoInvalido&&<p role="alert" className="mb-4 text-sm">La fecha inicial debe ser anterior o igual a la final.</p>}
    {!data?<p role="status" className="p-5 text-sm text-cdm-muted">Leyendo los pagos registrados…</p>:<><section className={`${surface} mb-5 grid grid-cols-2 gap-5 p-5 sm:grid-cols-3`}><Metric label={desde||hasta?"Pagado en el período":"Total del historial"} value={money(total)}/><Metric label="Pagos registrados" value={String(pagos.length)}/><Metric label="Saldo de acuerdos en pesos" value={money(deuda)} detail="Saldo actual, de todas las fechas"/></section>
      <p className="mb-4 text-xs text-cdm-muted">{desde||hasta?"Período filtrado":"Historial completo"} · {pagos.length} de {data.pagos.length} registros de pagos. Los nombres alternativos confirmados aparecen juntos.</p><div className="mb-4 flex flex-wrap gap-2"><button onClick={exportar} disabled={!pagos.length||!!error} className={`${control} inline-flex items-center gap-2`}><Download size={16}/>Exportar CSV</button><button onClick={()=>imprimir()} disabled={!pagos.length||!!error} className={`${control} inline-flex items-center gap-2`}><Printer size={16}/>Guardar PDF</button><button onClick={()=>void compartir()} disabled={!pagos.length||!!error} className={`${control} inline-flex items-center gap-2`}><Share2 size={16}/>Compartir resumen</button></div>{aviso&&<p role="status" className="mb-4 text-sm">{aviso}</p>}
      <div className={`${surface} overflow-hidden`}>{pagos.slice(0,limite).map(p=><article key={p.id} className="flex justify-between gap-4 border-b border-cdm-line p-4 last:border-0"><div className="min-w-0"><p className="text-sm font-semibold">{p.persona}</p><Link href={`/obras/${p.presupuestoId}/mano-obra`} className="mt-1 block text-sm underline decoration-cdm-line underline-offset-4">{p.obra}</Link><p className="mt-1 text-xs leading-relaxed text-cdm-muted">{p.descripcion||p.trabajo}</p><p className="mt-2 text-xs text-cdm-muted">{p.fecha} · {p.cuenta}</p></div><p className="shrink-0 text-sm font-semibold tabular-nums">{money(p.importe)}</p></article>)}{!pagos.length&&<p className="p-7 text-sm text-cdm-muted">No hay pagos en este período. Probá “Todo el historial”.</p>}</div>{pagos.length>limite&&<button className={`${control} mt-4`} onClick={()=>setLimite(n=>n+50)}>Ver más pagos ({pagos.length-limite})</button>}
      <details className={`${surface} mt-5 p-5`}><summary className="min-h-11 cursor-pointer font-semibold">Acuerdos y saldos por operario</summary>{acuerdos.map(a=><Link key={a.id} href={`/obras/${a.presupuestoId}/mano-obra`} className="flex flex-wrap justify-between gap-3 border-t border-cdm-line py-4 text-sm"><div><p className="font-semibold">{a.persona}</p><p className="mt-1 text-cdm-muted">{a.trabajo}</p>{a.notas&&<p className="mt-2 max-w-xl text-xs leading-relaxed text-cdm-muted">{a.notas}</p>}</div><div className="text-right tabular-nums"><p>{a.estado==="saldado"?"Saldado":`${a.moneda==="USD"?`US$ ${number(Math.abs(a.saldo))}`:money(Math.abs(a.saldo))} ${a.saldo<0?"pagados de más":"pendiente"}`}</p><p className="mt-1 text-xs text-cdm-muted">Acordado {a.moneda==="USD"?`US$ ${number(a.arreglado)}`:money(a.arreglado)} · {a.estado}</p>{a.pagosSinCotizacion>0&&<p className="mt-1 text-xs">{a.pagosSinCotizacion} pagos sin cotización USD</p>}</div></Link>)}</details>
      {(data.pagos.some(p=>p.persona==="Sin operario asignado"))&&<p className="mt-4 text-xs leading-relaxed text-cdm-muted">Hay pagos de mano de obra sin acuerdo u operario asignado. Figuran como “Sin operario asignado” hasta completar su vínculo.</p>}
    </>}
    <div style={{display:"none"}}><div ref={printRef}><p style={{letterSpacing:".3em"}}>R A V N .</p><h1>Resumen de pagos</h1><h2>{persona||"Todo el personal"}</h2><p>{desde||"Inicio del historial"} al {hasta||"hoy"}{obra?` · ${obras.find(([id])=>id===obra)?.[1]}`:""}</p><table><thead><tr><th>Fecha / operario</th><th>Obra y concepto</th><th>Medio</th><th>Importe ARS</th></tr></thead><tbody>{[...pagos].reverse().map(p=><tr key={p.id}><td>{p.fecha}<br/>{p.persona}</td><td>{p.obra}<br/>{p.descripcion||p.trabajo}</td><td>{p.cuenta}</td><td style={{whiteSpace:"nowrap"}}>{money(p.importe)}</td></tr>)}</tbody></table><h2>Total pagado: {money(total)}</h2><p>{pagos.length} pagos registrados. Emitido {todayBuenosAires()}.</p><p>Resumen informativo de pagos registrados. Los medios no informados se indican expresamente.</p></div></div>
  </div>;
}
