"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Download, Search } from "lucide-react";
import { todayBuenosAires } from "@/lib/cashflow-compute";
import { resumirGastosPersonales, categoriaPersonal, csvRegistros, type GastoPersonalRegistro } from "@/lib/finanzas-registros";
import { Metric, control, money, number, surface } from "./finance-ui";
import { useRealtimeTable } from "@/hooks/use-realtime-table";
import { descargarTexto } from "@/lib/descargar-texto";
export function GastosPersonales(){
  const hoy=todayBuenosAires();const [desde,setDesde]=useState(`${hoy.slice(0,7)}-01`),[hasta,setHasta]=useState(hoy);
  const [datos,setDatos]=useState<{desde:string;hasta:string;gastos:GastoPersonalRegistro[]}|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true);
  const [busqueda,setBusqueda]=useState(""),[categoria,setCategoria]=useState(""),[limite,setLimite]=useState(30);
  const cargar=useCallback(async(signal?:AbortSignal)=>{setLoading(true);try{const r=await fetch(`/api/finanzas/gastos?desde=${desde}&hasta=${hasta}`,{signal,cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error);setDatos(j);setError("");}catch(e){if(signal?.aborted)return;setError(e instanceof Error?e.message:"Sin conexión");}finally{if(!signal?.aborted)setLoading(false);}},[desde,hasta]);
  useEffect(()=>{const c=new AbortController();void cargar(c.signal);return()=>c.abort();},[cargar]);
  const actualizar=useCallback(()=>cargar(),[cargar]);useRealtimeTable("gastos_personales",actualizar);
  const rows=datos?.gastos??[];const resumen=useMemo(()=>resumirGastosPersonales(rows),[datos]);
  const filtrados=useMemo(()=>rows.filter(g=>(!categoria||categoriaPersonal(g.categoria)===categoria)&&`${g.concepto} ${g.cuenta}`.toLocaleLowerCase("es").includes(busqueda.toLocaleLowerCase("es"))),[datos,categoria,busqueda]);
  const totalFiltrado=filtrados.reduce((n,g)=>n+Math.round(g.monto*100),0)/100;
  const stale=datos&&(datos.desde!==desde||datos.hasta!==hasta);
  function exportar(){descargarTexto(`RAVN_gastos_personales_${datos?.desde}_${datos?.hasta}.csv`,csvRegistros(["Fecha","Concepto","Categoría","Importe ARS","Cuenta","Tipo","ID"],filtrados.map(g=>[g.fecha,g.concepto,categoriaPersonal(g.categoria),g.monto,g.cuenta,g.fijo_id?"Fijo pagado":g.extraordinario?"Extraordinario":"Variable",g.id])),"text/csv;charset=utf-8");}
  return <section aria-label="Gastos personales">
    <div className="mb-4 flex flex-wrap items-end gap-3"><label className="text-xs text-cdm-muted">Desde<input type="date" value={desde} onChange={e=>{setDesde(e.target.value);setLimite(30);}} className={`${control} mt-1 block`}/></label><label className="text-xs text-cdm-muted">Hasta<input type="date" value={hasta} onChange={e=>{setHasta(e.target.value);setLimite(30);}} className={`${control} mt-1 block`}/></label><button className={control} onClick={()=>{setDesde(`${hoy.slice(0,7)}-01`);setHasta(hoy);}}>Este mes</button><button className={control} onClick={()=>{setDesde(`${hoy.slice(0,4)}-01-01`);setHasta(hoy);}}>Este año</button></div>
    {error&&<p role="alert" className={`${surface} mb-4 p-4 text-sm`}>{error} <button className="underline" onClick={()=>void cargar()}>Reintentar</button></p>}
    {loading&&<p role="status" className="mb-3 text-sm text-cdm-muted">Actualizando gastos…</p>}
    {datos&&!stale&&<>
      <div className={`${surface} grid grid-cols-2 gap-5 p-5 sm:grid-cols-4`}><Metric label="Llevás gastado" value={money(resumen.total)} detail={`${resumen.cantidad} registros · ${datos.desde} a ${datos.hasta}`}/><Metric label="Gastos variables" value={money(resumen.variables)}/><Metric label="Fijos pagados" value={money(resumen.fijos)} detail="Pagos, no montos planificados"/><Metric label="Extraordinarios" value={money(resumen.extraordinarios)} detail="También incluidos en el total"/></div>
      <div className="my-4 grid gap-4 md:grid-cols-2"><div className={`${surface} p-5`}><h2 className="mb-4 text-base font-semibold">En qué se fue</h2>{resumen.categorias.length?resumen.categorias.map(c=><button key={c.nombre} aria-pressed={categoria===c.nombre} onClick={()=>{setCategoria(categoria===c.nombre?"":c.nombre);setLimite(30);}} className="mb-3 block min-h-11 w-full rounded-lg text-left focus-visible:outline-2"><span className="flex justify-between gap-3 text-sm"><span>{c.nombre}</span><span className="font-semibold tabular-nums">{money(c.total)} <span className="text-xs font-normal text-cdm-muted">· {number(c.pct)}%</span></span></span><span className="mt-2 block h-1.5 overflow-hidden rounded-full bg-cdm-fg/10"><span className="block h-full rounded-full bg-cdm-fg/70" style={{width:`${Math.min(100,Math.max(0,c.pct))}%`}}/></span></button>):<p className="text-sm text-cdm-muted">Sin gastos en este período.</p>}</div>
      <div className={`${surface} p-5`}><h2 className="text-base font-semibold">Cómo fue creciendo el gasto</h2><p className="mt-1 text-xs text-cdm-muted">Acumulado del período · tocá la línea para ver cada fecha</p>{resumen.dias.length>0&&<svg viewBox="0 0 400 140" className="mt-6 w-full overflow-visible" role="img" aria-label={`Gasto acumulado: ${money(resumen.total)}`}><line x1="0" y1="130" x2="400" y2="130" stroke="currentColor" opacity=".15"/><polyline fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinejoin="round" points={resumen.dias.map((d,i)=>`${i*400/Math.max(1,resumen.dias.length-1)},${130-d.acumulado/Math.max(1,resumen.total)*110}`).join(" ")}/>{resumen.dias.map((d,i)=><circle key={d.fecha} cx={i*400/Math.max(1,resumen.dias.length-1)} cy={130-d.acumulado/Math.max(1,resumen.total)*110} r="4" fill="currentColor"><title>{d.fecha}: {money(d.acumulado)} acumulado</title></circle>)}</svg>}<div className="mt-2 flex justify-between text-xs text-cdm-muted"><span>{datos.desde}</span><span>{datos.hasta}</span></div><Link href="/finanzas/presupuesto" className="mt-6 inline-flex min-h-11 items-center text-sm underline">Ver mi presupuesto y gastos fijos →</Link></div></div>
      <div className="mb-4 flex flex-wrap items-end gap-3"><label className="relative min-w-48 flex-1"><Search size={16} className="absolute left-3 top-3.5 text-cdm-muted"/><input aria-label="Buscar un gasto personal" placeholder="Buscar compra o cuenta" value={busqueda} onChange={e=>{setBusqueda(e.target.value);setLimite(30);}} className={`${control} w-full pl-9`}/></label><select aria-label="Filtrar categoría" value={categoria} onChange={e=>{setCategoria(e.target.value);setLimite(30);}} className={control}><option value="">Todas las categorías</option>{resumen.categorias.map(c=><option key={c.nombre}>{c.nombre}</option>)}</select><button className={`${control} inline-flex items-center gap-2`} disabled={!filtrados.length||loading||Boolean(error)} onClick={exportar}><Download size={16}/>Exportar</button></div>
      <p className="mb-3 text-sm text-cdm-muted">{filtrados.length} gastos · {money(totalFiltrado)}{categoria?` · ${categoria}`:""}</p>
      <div className={`${surface} overflow-hidden`}>{filtrados.slice(0,limite).map(g=><div key={g.id} className="flex items-start justify-between gap-4 border-b border-cdm-line px-4 py-4 last:border-0"><div className="min-w-0"><p className="text-sm font-medium">{g.concepto}</p><p className="mt-1 text-xs leading-relaxed text-cdm-muted">{g.fecha} · {categoriaPersonal(g.categoria)} · {g.cuenta}{g.fijo_id?" · Fijo pagado":g.extraordinario?" · Extraordinario":""}</p></div><p className="shrink-0 text-sm font-semibold tabular-nums">{money(g.monto)}</p></div>)}{!filtrados.length&&<p className="p-6 text-sm text-cdm-muted">No hay gastos para estos filtros.</p>}</div>{filtrados.length>limite&&<button className={`${control} mt-4`} onClick={()=>setLimite(n=>n+50)}>Ver más gastos ({filtrados.length-limite})</button>}
    </>}
  </section>;
}
